import os
from datetime import datetime, timedelta, timezone

BJ_TZ = timezone(timedelta(hours=8))


def main():
    now = datetime.now(BJ_TZ)
    print(f"  生成维护报告 — {now.strftime('%Y-%m-%d %H:%M:%S UTC+8')}")

    report = f"""\
# 🔧 Maintenance Report

- **Date**: {now.strftime('%Y-%m-%d %H:%M UTC+8')}
- **Status**: ✅ Active

This repository is actively maintained. The automated workflow runs as expected.

---
*Auto-generated by GitHub Actions*
"""

    os.makedirs("reports", exist_ok=True)
    filename = f"reports/maintenance_{now.strftime('%Y-%m')}.md"

    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"  ✔ 维护报告已生成: {filename}")


if __name__ == "__main__":
    main()
